# This is a basic workflow to help you get started with Actions

name: crtsh

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  crtsh:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: crtsh
        run: |
          wget https://gist.githubusercontent.com/hellowork-mhlw/187e078b3ac4589be11ddf8d040d8ab9/raw/b315ad4dc57d3a4f208fe21baf85df50d0fa345d/domains.txt
          for domain in `cat domains.txt`; do grep -n $domain domains.txt; time curl https://crt.sh/?q=$domain | grep -Po '[\w-.]*'$domain | sort | uniq | wc -l; done
